steps:
- id: go_linter
  name: "golangci/golangci-lint"
  args: ["golangci-lint","run", "--deadline", "5m0s"]
- id: go_test
  name: "golang:1.12.6"
  args: ["go", "test","./..."]
  env: [
    "PROJECT_ROOT=github.com/ninnemana/hue-exporter",
    "GO111MODULE=on",
  ]
- id: go_security
  name: "securego/gosec"
  args: ["."]
  env: ["PROJECT_ROOT=github.com/ninnemana/hue-exporter"]
- name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '--platform linux/arm/v7,linux/arm64/v8,linux/amd64',
    '-t',
    'gcr.io/$PROJECT_ID/hue-exporter:$SHORT_SHA',
    '-f',
    'Dockerfile',
    '.'
  ]
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - '[[ "$BRANCH_NAME" == "master" ]] && docker tag gcr.io/$PROJECT_ID/hue-exporter:$SHORT_SHA gcr.io/$PROJECT_ID/hue-exporter:latest || echo pass && true'
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
    - '-c'
    - '[[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/$PROJECT_ID/hue-exporter || echo pass && true'

