name: WIP
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
    
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        args: --timeout 5m0s

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    
    - run: go test ./...
