name: WIP
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: GolangCI-Lint Action
      uses: actions-contrib/golangci-lint@v0.1.0
    
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    
    - run: go test ./...
